package org.commcare.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ListAdapter;
import android.widget.ListView;

import org.commcare.activities.CommCareActivity;
import org.commcare.adapters.EntitySubnodeDetailAdapter;
import org.commcare.cases.entity.Entity;
import org.commcare.cases.entity.NodeEntityFactory;
import org.commcare.dalvik.R;
import org.commcare.suite.model.Detail;
import org.commcare.tasks.EntityLoaderListener;
import org.commcare.tasks.EntityLoaderTask;
import org.commcare.views.EntityView;
import org.javarosa.core.model.instance.TreeReference;

import java.util.List;

import androidx.appcompat.app.AppCompatActivity;

/**
 * Created by jschweers on 8/26/2015.
 * <p/>
 * An EntityDetailSubnodeFragment displays a detail with a row for each of a set of
 * nodes generated by expanding a given nodeset expression in the context of a given entity.
 */
public class EntitySubnodeDetailFragment extends EntityDetailFragment implements EntityLoaderListener {
    private EntityLoaderTask loader;
    private ListView listView;

    public EntitySubnodeDetailFragment() {
    }

    /**
     * Inflates and initializes the fragment's view for displaying an entity's detail list.
     * <p>
     * Restores instance state and retrieves the detail and reference for display. If neither
     * the adapter nor the loader is set and the fragment is not already attached to an activity,
     * an asynchronous loader task is initiated to fetch entity data. In this case, a header row
     * is built from the detail fields and added to the view.
     * </p>
     *
     * @param inflater the LayoutInflater used to inflate the layout
     * @param container the parent view for the fragment's UI
     * @param savedInstanceState a Bundle containing previous state, if available
     * @return the root View for the fragment's user interface
     */
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (savedInstanceState != null) {
            this.modifier = savedInstanceState.getParcelable(MODIFIER_KEY);
        }

        Detail detailToDisplay = getDetailToUseForDisplay();
        TreeReference referenceToDisplay = getReferenceToDisplay();

        View rootView = inflater.inflate(R.layout.entity_detail_list, container, false);

        final AppCompatActivity thisActivity = (AppCompatActivity)getActivity();
        this.listView = rootView.findViewById(R.id.screen_entity_detail_list);

        if (this.adapter == null && this.loader == null && !EntityLoaderTask.attachToActivity(this)) {
            // Set up task to fetch entity data
            EntityLoaderTask theLoader =
                    new EntityLoaderTask(detailToDisplay, null, getFactoryContextForRef(referenceToDisplay));
            theLoader.attachListener(this);
            theLoader.executeParallel(detailToDisplay.getNodeset().contextualize(referenceToDisplay));

            // Add header row
            final LinearLayout headerLayout = rootView.findViewById(R.id.entity_detail_header);
            String[] headers = new String[detailToDisplay.getFields().length];
            for (int i = 0; i < headers.length; ++i) {
                headers[i] = detailToDisplay.getFields()[i].getHeader().evaluate();
            }
            EntityView headerView = EntityView.buildHeadersEntityView(thisActivity, detailToDisplay,
                    headers, false);
            headerLayout.removeAllViews();
            headerLayout.addView(headerView);
            headerLayout.setVisibility(View.VISIBLE);
        }

        return rootView;
    }

    @Override
    public void attachLoader(EntityLoaderTask task) {
        this.loader = task;
    }

    /**
     * Delivers the results of an entity data load operation and updates the subnode detail view.
     * <p>
     * This method retrieves the correct detail from the session—using a child detail if indicated by the arguments—
     * resets the loader, and creates a new adapter to display the loaded entities and their associated references.
     * The list view is then updated with the new adapter, and if a valid focus target index is provided, the view
     * is scrolled to bring the specified item into focus.
     * </p>
     *
     * @param entities list of loaded entities
     * @param references list of tree references corresponding to the entities
     * @param factory factory for constructing node entities
     * @param focusTargetIndex index to scroll to, or -1 if no scrolling is required
     */
    @Override
    public void deliverLoadResult(List<Entity<TreeReference>> entities, List<TreeReference> references,
            NodeEntityFactory factory, int focusTargetIndex) {
        Bundle args = getArguments();
        Detail detail = asw.getSession().getDetail(args.getString(DETAIL_ID));
        final int thisIndex = args.getInt(CHILD_DETAIL_INDEX, -1);
        final boolean detailCompound = thisIndex != -1;
        if (detailCompound) {
            detail = getChildDetailForDisplay(detail, thisIndex);
        }

        this.loader = null;
        this.adapter = new EntitySubnodeDetailAdapter(getActivity(), detail, references,
                entities, modifier, factory);
        this.listView.setAdapter((ListAdapter)this.adapter);
        if (focusTargetIndex != -1) {
            listView.setSelection(focusTargetIndex);
        }
    }

    /**
     * Handles load errors by forwarding the exception to the parent activity for display.
     *
     * <p>This method casts the current activity to a CommCareActivity and calls its error display method
     * to notify the user of the issue encountered during data loading.</p>
     *
     * @param e the exception that occurred during the data loading process
     */
    @Override
    public void deliverLoadError(Exception e) {
        ((CommCareActivity)getActivity()).displayCaseListLoadException(e);
    }

    /**
     * Receives progress updates during entity loading.
     *
     * <p>This implementation intentionally does nothing as progress updates are not
     * needed for the subnode detail display logic.</p>
     *
     * @param values an array of progress indicators (unused)
     */
    @Override
    public void deliverProgress(Integer[] values) {
        // nothing to do
    }
}
